### PR TITLE
RxJava is on the public API so the library needs to declare it as such

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by mikaelm12** [comment]
Actually I want to verify this manually as well. Let's wait until that happens to merge this.

**Comment by mikaelm12** [comment]
I'll verify this today and we can merge when I re-approve

**Comment by mikaelm12** [comment]
Rebase this on release/2.2 now that I've reverted the super POM stuff

**Comment by BrennanConroy** [comment]
Done

**Comment by BrennanConroy** [comment]
@mikaelm12 Ping

**Comment by anurse** [comment]
@mikaelm12 mentioned in stand-up that he verified this. So it's good to merge.

**Pull request merged**
