### PR TITLE
Prkrishn/test

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test

**Comment by pranavkm** [comment]
@dotnet-bot test

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build (Spanish language image) please

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by pranavkm** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
Looks like the failure is caused by a regression caused by NodeJS 9. Rollup was depending on buggy behavior and now it fails: https://github.com/rollup/rollup/issues/1782 .

The options are:

1. Downgrade from Node 9 to Node 8
2. Replace rollup with webpack (been on my queue for a little bit now)


I'll take a quick stab at 2, but we may have to do 1 if it's going to be complicated...

**Comment by anurse** [comment]
Replacing rollup isn't going to be trivial. It's probably still a good idea, but it won't be trivial :(.

**Comment by BrennanConroy** [comment]
This change is in dev now

**Pull request closed without merging**
