### PR TITLE
Reduce LongPolling timeout to accommodate Cloudflare's timeout

### PR DESCRIPTION
**Pull request by mikaelm12**
Issue: https://github.com/aspnet/SignalR/issues/1357
Cloudflare has a timeout of only 100 seconds after which they close the connection. Detailed here: https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred

### CODE REVIEW

**Comment by anurse** [comment]
Hrm. A little concerned that we don't have a test for the actual timeout behavior. The test in here is a little contrived...

**Comment by davidfowl** [comment]
That’s unrelated to this change. We should have to test to very that timeouts work  (I’m surprised we don’t tbh)

**Comment by anurse** [comment]
Yeah, I agree. Just pointing that out.

**Comment by davidfowl** [comment]
We do have a test:

https://github.com/aspnet/SignalR/pull/538/files#diff-feef691b2b3ce98f9972dd0ab49dea5eR316

**Comment by anurse** [comment]
Yeah, and I suppose it isn't really feasible to test the exact timeout because of how our unit tests run. Ok, I'm good with what we've got so far.

**Pull request merged**
