### PR TITLE
Moving TS client to a dedicated subfolder

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by mikaelm12** [comment]
Sorry but whats the purpose behind this again?

**Comment by moozzyk** [comment]
To keep the project root clean and have one folder for all TS client related changes.

**Comment by mikaelm12** [comment]
So this will be the strategy for all the additional clients moving forward then as well I'm assuming?

**Comment by mikaelm12** [comment]
Anyways the changes look pretty good to me but I'll let someone more confident in their csproj abilities sign off 😄

**Comment by BrennanConroy** [comment]
:shipit:

**Comment by moozzyk** [comment]
@mikaelm12 - we decided that only TS client will be in this repo but we don't want npm to pollute the tree - especially the root.

**Pull request merged**
