### PR TITLE
polyfill UInt8Array.forEach for IE

### LINKED ISSUE #1979: Verify Browser Tests in IE
They're broken, I think because of UInt8Array.forEach not existing. I can easily polyfill. Filing this to track.

### PR DESCRIPTION
**Pull request by anurse**
Fixes #1979 

image

### CODE REVIEW

**Comment by mikaelm12** [comment]
I'm actually seeing a number of falky failures in the browser tests in IE. I get between 2 and 7 failures every run from this branch.

**Comment by anurse** [comment]
I've noticed some odd behavior with IE throwing "SecurityError" or blocking HTTP requests sometimes. I'm not yet sure if it's something we're doing wrong or something IE is doing wrong...

**Comment by anurse** [comment]
We can open a new issue to track those though.

**Comment by moozzyk** [comment]
AFAIK "Security error" on IE just means you have reached connection limit (e.g.: https://github.com/SignalR/SignalR/pull/2112)

**Comment by anurse** [comment]
Hrm, the tests shouldn't be running in parallel though so I'm not sure how we're running out.

**Pull request merged**
