### PR TITLE
Use params passed into HubConnectionBuilder (#2223)

### PR DESCRIPTION
**Pull request by mikaelm12**
Issue: https://github.com/aspnet/SignalR/issues/2219

### CODE REVIEW

**Comment by davidfowl** [comment]
You should get at least one person to review it

**Comment by anurse** [comment]
This is just the merge to `dev` right?

**Comment by mikaelm12** [comment]
Yeah

**Comment by mikaelm12** [comment]
This was shiproom approved for RTM yesterday

**Pull request merged**
