### PR TITLE
Change package name to com.microsoft.signalr

### PR DESCRIPTION
**Pull request by mikaelm12**
Changing the package name from `com.microsoft.aspnet.signalr` to `com.microsoft.signalr`
Fixes: #3091
//cc @JonathanGiles look at what we're doing!

### CODE REVIEW

**Comment by anurse** [comment]
Don't forget to link the issue 😸

**Comment by JonathanGiles** [comment]
Great work! My powers know no limits :-)

**Comment by mikaelm12** [comment]
// cc @muratg just to make sure it's visible that we're changing the package name

**Comment by anurse** [comment]
We've got the approval so as long as everything builds correctly we should be able to ship to this groupId.

**Comment by anurse** [comment]
@mikaelm12 when this is merged, please post to aspnet/Announcements describing the upcoming change in preview3. Make sure to follow the pattern of creating an issue on aspnet/SignalR to discuss the change and locking the Announcements issue (to avoid spamming the people following that repo)

**Pull request merged**
