### PR TITLE
[automated] Update branding for 3.0

### PR DESCRIPTION
**Pull request by natemcmaster**
Part of https://github.com/aspnet/Home/issues/3278.
This should updates the branding to the next major version

### CODE REVIEW

**Comment by muratg** [comment]
@DamianEdwards for the versioning question. When it's 2.0, we'll have some customer confusion in our hands (ASP.NET SignalR 2.x vs ASP.NET Core SignalR 2.x) 

cc @anurse

**Comment by anurse** [comment]
I think we had decided to just bite the bullet and jump to `3.0` for SignalR. I still also believe `1.0` was the right version number at release for the same reason (avoiding confusion with ASP.NET SignalR 2.x).

**Comment by natemcmaster** [comment]
Ok, i'll update the PR to change branding to 3.0. I'll get positive confirmation from @DamianEdwards before merging.

**Comment by natemcmaster** [comment]
Confirmed in person with @anurse. 3.0.0 here we go!

**Pull request merged**
