### PR TITLE
Increase the size of the WebSockets buffer to 4K.

### PR DESCRIPTION
**Pull request by mikaelm12**
Addresses issue: https://github.com/aspnet/SignalR/issues/271

### CODE REVIEW

**Comment by grahamehorner** [comment]
I'm wondering why hardcode the buffer size; should it not be configurable ? with a default value of 4k

**Comment by moozzyk** [comment]
Do tests need to be updated? I remember we had tests whose messages sizes were specifically chosen to fit/not fit multiple buffers.

**Comment by mikaelm12** [comment]
> I'm wondering why hardcode the buffer size; should it not be configurable ?

We discussed this, no one felt strongly about it and we decided unless there was a demonstrated interest configuring the buffer size we would just leave it at 4k. That being said we can still change it 😄

**Comment by mikaelm12** [comment]
@moozzyk 

>  I remember we had tests whose messages sizes were specifically chosen to fit/not fit multiple buffers.

Good point. I'll update the EndToEnd tests

**Comment by grahamehorner** [comment]
what would be the impact of a 4k buffer for a high volume service that is only using 256byte messages?
or a service that is using messages larger than 4k ? would GC be working overtime? allocating 4k buffers for a small messages?

**Comment by moozzyk** [comment]
YAGNI. SignalR 2.x has been running with a 4K buffer for webSocket messages from the very beginning and no one has reported any problems with that. If this turns out to be an issue we can think of making it configurable but we should not do this now. Note that this is on the client and not on the server.

**Comment by davidfowl** [comment]
> what would be the impact of a 4k buffer for a high volume service that is only using 256byte messages?
or a service that is using messages larger than 4k ? would GC be working overtime? allocating 4k buffers for a small messages?

Would need to be measured. Historically we don't worry about it as much on the client side but the downside of the entire API surface here is that we're pinning the 4K buffer during the length of the async read.

The other bigger issues with this code IMO are the fact that we're making a new buffer and a new list of buffers per read. On top of that we're not using pooled buffers. In short, this code needs to be  profiled and potentially overhauled in the long run. The initial goal was to get it up and running then we can optimize.

**Comment by grahamehorner** [comment]
I'm happy to do some profiling to assist the team, I agree @davidfowl the allocation of memory read with no memory pooling could cause client side issues especially in this new world of multi-platform .NET where devices such as Raspberry PI has a smaller amount memory where memory fragmentation may be an issues, and the GC would need to run more frequently.

IMO some issues could be reduced if the buffer size was configurable; happy to test with some of the use cases we have on low memory devices.

**Pull request merged**
