### PR TITLE
Rename HttpTransportType

### PR DESCRIPTION
**Pull request by mikaelm12**
API review task
HttpTransportType -> HttpTransportTypes

### CODE REVIEW

**Comment by JamesNK** [comment]
Ehh. Pluralization make sense on the external APIs because a dev is specifying a number of transport types, but internally SignalR tends to use it without flags to select a single transport 🤷‍♂️

**Comment by mikaelm12** [comment]
> but internally SignalR tends to use it without flags to select a single transport

Yeah, I agree. That does feel weird.

**Comment by davidfowl** [comment]
I vote no. I didn’t like it in the meeting either

**Comment by mikaelm12** [comment]
Alright. Closing this then

**Pull request closed without merging**
