### PR TITLE
create a version of @aspnet/signalr-client that hard-breaks

### PR DESCRIPTION
**Pull request by anurse**
We still get some people trying to use `@aspnet/signalr-client`. It's marked deprecated on NPM: https://www.npmjs.com/package/@aspnet/signalr-client but I'm not sure that's "hard" enough. This is an idea for a version that completely fails to install, with an error indicating that you need to use `@aspnet/signalr` instead.

Thoughts? I don't actually plan to merge this into our code, it's just a convenient way to look at and review the way it works. Here's sample output:

```
ps1› npm install C:\Users\anurse\Code\aspnet\SignalR\clients\ts\signalr-client-deprecated\signalr-client-1.0.0-alpha2-update1.tgz

> signalr-client@1.0.0-alpha2-update1 install C:\Tmep\node_modules\signalr-client
> echo "This package has been deprecated. Use '@aspnet/signalr' instead." && exit 1

"This package has been deprecated. Use '@aspnet/signalr' instead."
npm WARN enoent ENOENT: no such file or directory, open 'C:\Tmep\package.json'
npm WARN Tmep No description
npm WARN Tmep No repository field.
npm WARN Tmep No README data
npm WARN Tmep No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! signalr-client@1.0.0-alpha2-update1 install: `echo "This package has been deprecated. Use '@aspnet/signalr' instead." && exit 1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the signalr-client@1.0.0-alpha2-update1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anurse\AppData\Roaming\npm-cache\_logs\2018-04-17T15_56_31_947Z-debug.log
```

### CODE REVIEW

**Comment by anurse** [comment]
> We still get some people trying to use @aspnet/signalr-client. **It's marked deprecated on NPM: https://www.npmjs.com/package/@aspnet/signalr-client but I'm not sure that's "hard" enough.**

**Comment by davidfowl** [comment]
Do both?

**Comment by davidfowl** [comment]
Sure do this.

**Comment by anurse** [comment]
I'll also be sure to deprecate this new version :trollface:

**Comment by anurse** [comment]
This is done: https://www.npmjs.com/package/@aspnet/signalr-client

**Pull request closed without merging**
