### PR TITLE
Reacting to CoreFxLab package changes

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @BrennanConroy \ @davidfowl \ @anurse

**Comment by davidfowl** [comment]
Why is the ci red?

**Comment by BrennanConroy** [comment]
... https://github.com/aspnet/SignalR/tree/brecon/dev-gate
Needs more work, tests are hanging

**Comment by davidfowl** [comment]
Can somebody explain how this works?

**Comment by BrennanConroy** [comment]
Pull newer packages to your machine and make the project work?

**Comment by davidfowl** [comment]
Closing In favor of https://github.com/aspnet/SignalR/pull/110/files

**Comment by pranavkm** [comment]
> Can somebody explain how this works? I'm guessing the name dev-gate is significant

We build a gated branch in CoreCLR in case there's breaking changes we need to react to. This way the dev branch isn't broken until we've picked up new packages.

**Pull request closed without merging**
