### PR TITLE
Throw InvalidDataException instead of FormatException in NegotationProtocol

### PR DESCRIPTION
**Pull request by jackjwilliams**
Throw InvalidDataException instead of FormatException in NegotationProtocol

 - Modify NegotiationProtocol to throw InvalidDataException
 - Update NegotiationProtocolTests expectations
 - Remove test case for InlineData "Missing required property 'protocol'"

Addresses #1203

@anurse It took me a minute to figure out why one case failed for `[InlineData("{}\u001e", "Missing required property 'protocol'.")]`, it was because the test was expecting a FormatException from JsonUtils.GetRequiredProperty (which is still a valid case). 

I've removed it for now, but removing test cases is usually frowned upon. So I can account for the FormatException from JsonUtils.GetRequiredProperty and re-work the test some if you want.

### CODE REVIEW

**Comment by anurse** [comment]
> it was because the test was expecting a FormatException from JsonUtils.GetRequiredProperty (which is still a valid case).

Actually, go ahead and change the exceptions in `JsonUtils` to `InvalidDataException` as well, which should allow you to restore the test case (it might mean some other test cases need to be updated too). We shouldn't really be using `FormatException` anywhere since it's specifically designed for `string.Format` and related APIs.

Looking good so far! The Travis failure is a flaky test that we've seen fail off-and-on, so it's not related to your change. If it fails again when you update the PR, I can rerun it until it passes (which may be the definition of insanity, but hey, it usually does the trick)

**Comment by anurse** [comment]
Thanks! Change looks good so far, we'll see how the build shakes out (some of the tests are a bit flaky, but I can re-run them if they fail)

**Comment by BrennanConroy** [comment]
Ping @anurse 
Good to merge?

**Comment by anurse** [comment]
Yep. Thanks for the contribution @jackjwilliams !

**Comment by jackjwilliams** [comment]
@anurse No problem, was a good learning experience!

**Pull request merged**
