### PR TITLE
Adding support for Hub and HubMethod [Authorize]

### PR DESCRIPTION
**Pull request by berdon**
- Allows for implicit method protection with [Authorize] on Hub
- Allows for [AllowAnonymous] to allow unauthorized access on protected Hub

Addresses #256 

Sneak peak / first draft for authorization implementation on Hub and Hub Methods. I'm hoping this is in alignment with the changes @BrennanConroy is doing in #254 / #255 and doesn't step on any toes there.

I added test cases and updated the ChatSample to include a Role requirement. Presently, [Authorize] on Hub is mostly useful for protecting all underlying methods as it doesn't prevent a connection unlike `EndPointOptions<>.AuthorizationPolicyNames`. There's some loose ends too on what, if at all, Authentication and Challenging looks like within the Hub context.

### CODE REVIEW

**Comment by berdon** [comment]
Adding more tests around the AuthorizeAttribute:
- Named policies
- Role requirements

**Comment by davidfowl** [comment]
Hey @berdon thanks for the pull request! I think the authorize attribute on the hub should map conceptually to end point auth.

**Comment by berdon** [comment]
@davidfowl 

I had actually originally done that by adding the mapping in the extension method to set the `IEndPointOptions` to whatever `IAuthorizeData` was applied to the Hub. I didn't do that for two reasons:

1. Conceptually, that stage is different: authorization at that stage allows for skipping a "connection" entirely
2. Because of 1, overriding the default Hub AuthorizeAttribute becomes difficult because `EndPoint` has no notion of underlying `HubEndPoint` AuthorizeAttribute`s. It would _need_ to have knowledge to know whether it should forgo a connection or not.

I think it actually makes sense to have three stages of authorization:
- EndPoint
- Hub
- Hub Methods

When @BrennanConroy adds in the HubEndPoint it could still allow for setting the AuthorizationPolicy in that as well.

**Comment by davidfowl** [comment]
While I understand that is conceptually true I'm saying that we should be doing 2 kinds, EndPoint and Hub Methods. We need the plumbing so that endpoints can advertise without hardcoding the policy via options. Maybe an auth selector so that the HubEndPoint can advertise the correct `IAuthorizeData`. 

The reason I want this to *just* work is so that http authentication works by default and when it works, the second level Hub is redundant.

**Comment by grahamehorner** [comment]
I think it would be nice if the endpoint/hub authorisation attribute had a option such as RequireSecureConnection allowing hub to be exposed only on the endpoint it was designed/written for;  as this gives added safeguard when deploying of hubs, should the endpoint be incorrectly configured (for any reason) and therefor preventing data leak as the hub would simply refuse connection giving a  WEB_SOCKET_ENDPOINT_UNAVAILABLE_CLOSE_STATUS    = 1001

[Authorize(RequireSecureConnection=true, Roles = "Moderator")]

IMO this also becomes important when using DependencyInjection of hubs created by 3rd parties as they may need to enforce a secured connection to they hub.

**Comment by davidfowl** [comment]
@berdon lets do the 2 pieces of auth we agree on, what you have is good here. I just want you to remove the Hub level auth or now. We can discuss that on the issue. I think [this comment]( https://github.com/aspnet/SignalR/pull/386#issuecomment-294246476) should be moved to https://github.com/aspnet/SignalR/issues/256 so we can continue discussing it there. 

This also needs a rebase. Let me know if you can do it otherwise I can just take it over.

**Comment by berdon** [comment]
I'll rebase and get this cr updated.

**Comment by davidfowl** [comment]
@berdon This may be a bit more challenging with the layering changes. I'm going to do some more refactoring here to make things a bit clearer.

**Pull request closed without merging**
