### PR TITLE
Update Gradle to 4.9

### PR DESCRIPTION
**Pull request by mikaelm12**
Running into an issue described here: https://github.com/gradle/gradle/issues/4931
Upgrading to a version greater than or equal to 4.8 (4.9 in this case) should fix it.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Did we get OSS approval for the new version of Gradle?

**Comment by mikaelm12** [comment]
> Did we get OSS approval for the new version of Gradle?

Do we have to do this for new versions? I wasn't aware.
@muratg Can we get this process started?

**Comment by anurse** [comment]
Yes, we should register this. FYI though, this change fixes build failures, so it's fairly high priority.

**Comment by mikaelm12** [comment]
@muratg Does that mean this has been OSS approved?

**Comment by muratg** [comment]
@mikaelm12 No, perhaps @anurse or @Eilon can help.

**Comment by mikaelm12** [comment]
@anurse and I submitted Gradle 4.9 in the OSS approval tool. Going to merge this now 👍

**Pull request merged**
