### PR TITLE
add net451 support to signalr.redis

### PR DESCRIPTION
**Pull request by searus**
net451 framework was missing from the SignalR.Redis project

### CODE REVIEW

**Comment by moozzyk** [comment]
Thanks. I ordered usings, rebased and merged as 4158dfed8ff090927761466b062de3db5aed946f

**Comment by searus** [comment]
Do you know when this will be pushed as a NuGet package?

**Comment by BrennanConroy** [comment]
It already is https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.SignalR.Redis

**Comment by searus** [comment]
you guys are awesome 👍 
Thanks!

**Pull request closed without merging**
