### PR TITLE
Fix NuGet downgrade warnings

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
Any idea why tests are failing on Ubuntu? Is this a known issue?

**Comment by moozzyk** [comment]
No. I see we had an [issue](https://github.com/aspnet/SignalR/issues/215) once with this test after moving to a different pipelines version but not recently. 
Is it consistent?

**Comment by pranavkm** [comment]
@moozzyk I spoke to @BrennanConroy and he said this was a known flaky test.

**Comment by moozzyk** [comment]
I have not seen this fail recently so was not aware. I was ware of: https://github.com/aspnet/SignalR/issues/608. I will create an issue - we need to look at these flaky tests.

**Comment by pranavkm** [comment]
@BrennanConroy ?

**Comment by moozzyk** [comment]
Opened #618 to investigate this.

**Pull request merged**
