### PR TITLE
Removing transport fallback in the client

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by davidfowl** [comment]
Time to get some async await!

**Comment by moozzyk** [comment]
Yes, once we move from .NET 4 errrr ES6

**Comment by davidfowl** [comment]
Typescript 2.1.1 allows down level compilation from async await to ES3

**Comment by moozzyk** [comment]
I added this to the [list](https://github.com/aspnet/SignalR/issues/3) and will see if it feasible but it's not a priority ATM (need tests first)

**Pull request merged**
