### PR TITLE
Re-enable Windows dotnet-ci builds

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by davidfowl** [comment]
@pranavkm did it work?

**Comment by pranavkm** [comment]
Unfortunately not. It kept telling me it couldn't find the log folder. The last build failed because it could not find NETFx framework assemblies which is strange.

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by anurse** [comment]
@pranavkm you know what the definition of insanity is right? :trollface:

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by JohnTortugo** [comment]
@dotnet-bot test Windows Release x64 Build please

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by pranavkm** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by JohnTortugo** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by JohnTortugo** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by JohnTortugo** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by JohnTortugo** [comment]
@dotnet-bot test Windows Release x64 Build please.

**Comment by JamesNK** [comment]
Should this go into release/2.1?

**Comment by JamesNK** [comment]
FYI the artifacts only contain test logs for .NET Framework. There are no .NET Core test logs. Compare the new build's artifacts with appveyor's to see the difference.

**Comment by pranavkm** [comment]
@JamesNK fixed - https://ci3.dot.net/job/aspnet_SignalR/job/dev/job/windows-Configuration_Release_prtest/574/artifact/netci-archived-logs/Microsoft.AspNetCore.Http.Connections.Tests/.

**Pull request merged**
