### PR TITLE
Update build to Node 10 and use `npm ci`

### LINKED ISSUE #2817: Update build to use `npm ci` to improve reliability
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

This is not yet available in Node 8.x (see https://github.com/nodejs/node/pull/21593).

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #2817 

Changes:
* Set minimum node version to 10.9 (requires TeamCity updates)
* Use `npm ci` in CI builds instead of `npm install`

### CODE REVIEW

**Comment by anurse** [comment]
@BrennanConroy this looks like the orphaned ping timer issue we saw earlier. This should have been resolved earlier right?

**Comment by BrennanConroy** [comment]
Yeah, we added the connected check before the ping. So there may be another bug here

**Comment by natemcmaster** [comment]
ok. re-triggered the PR with latest changes from 2.2

**Comment by natemcmaster** [comment]
Still getting the same errors.

**Comment by BrennanConroy** [comment]
Yeah super strange, seems to consistently repro on VSTS when you upgrade node. Can't hit it locally with 10.9.0

**Comment by natemcmaster** [comment]
I'm closing this for now because I don't want to deal with the hassle of updating TeamCity agents. Will re-address when we finish the VSTS move.

**Pull request closed without merging**
