### PR TITLE
Added Microsoft.AspNetCore.SignalR.Protocols.Json

### PR DESCRIPTION
**Pull request by davidfowl**
- Fixed package descriptions
- Call AddJsonProtocol from both the SignalR.Core (client and server)

Fixes https://github.com/aspnet/SignalR/issues/1856

### CODE REVIEW

**Comment by JamesNK** [comment]
Should protocol tests be moved from Microsoft.AspNetCore.SignalR.Common.Tests into their own assemblies. I don't really care.

**Comment by davidfowl** [comment]
> Should protocol tests be moved from Microsoft.AspNetCore.SignalR.Common.Tests into their own assemblies. I don't really care.

Yea, we can file a task to clean up the test structuring, it seems like we got lazy at some point and started throwing shit in the same assemblies.

**Comment by halter73** [comment]
I'll fix the actual benchmarks repo. That comment was so nitty, I'm now embarrassed for having left it 😄

**Pull request merged**
