### PR TITLE
Don't log message data

### PR DESCRIPTION
**Pull request by mikaelm12**
Issue: https://github.com/aspnet/SignalR/issues/1449
We don't want to log message content on the client.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Pretty sure there are more locations that we need to change.

**Comment by davidfowl** [comment]
Also tests?

**Comment by davidfowl** [comment]
It comes down to understanding how important this change is. If another change regresses this I have extremely low confidence that we'll catch it in a code review.

**Comment by davidfowl** [comment]
@anurse and @mikaelm12 can you talk to @anpete and @ajcvickers about how EF handles logging of parameter values?

**Comment by mikaelm12** [comment]
Not working on the atm.

**Pull request closed without merging**
