### PR TITLE
Fix dynamic require for Webpack

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/SignalR/issues/3254

@muratg We'd like to discuss the release timeline for this fix as it's a broken scenario when using Angular 6+.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
@anurse Couldn't extract this into a function as webpack needs to know the string value passed into `require` otherwise it complains.

**Comment by anurse** [comment]
> it's a broken scenario when using Angular 6+

It's also a regression. 2.1 did not have this problem and would have worked from Angular 6.

**Comment by muratg** [comment]
Also, should this go to master? Or does master not have this problem?

**Comment by anurse** [comment]
Yes, this will go up to master as well.

**Comment by vivmishra** [comment]
Approved for 2.2.1

**Comment by natemcmaster** [comment]
Before this merges, we need to update branding on this repo. Please wait to merge until that is in.

**Comment by BrennanConroy** [comment]
I'm assuming branding is done and I can push? @natemcmaster

**Pull request merged**
