### PR TITLE
try just removing the jenkins files?

### PR DESCRIPTION
**Pull request by anurse**
Not 100% sure if we can just remove these files or if Jenkins will start complaining if we do that. Easiest way to figure that out is to try :).

Azure DevOps (AzDO) is providing enough coverage for us now and we don't need the extra Jenkins builds. We are losing the Spanish-language build but we can get that back through AzDO (#3211 is tracking that).

Part of #3211

### CODE REVIEW

**Comment by anurse** [comment]
Looks removing the files doesn't disable the trigger. @pranavkm @natemcmaster @ryanbrandenburg, any of you know how to disable Jenkins for this repo?

**Comment by pranavkm** [comment]
Likely this - https://github.com/dotnet/dotnet-ci/blob/master/data/repolist.txt#L320-L322

cc @mmitche

**Comment by anurse** [comment]
https://github.com/dotnet/dotnet-ci/pull/1073

**Comment by mmitche** [comment]
@dotnet-bot test this please (shouldn't do anything)

**Comment by anurse** [comment]
I'm going to close this and open a new PR. I just want to satisfy my paranoia that .NET CI doesn't trigger. Matt's comment was good, but I'd like to double check and actually see a PR without the Jenkins checks at all before finalizing ;P

**Pull request closed without merging**
