### PR TITLE
fix #1155 by renaming signalRTokenHeader to access_token (#1343)

### LINKED ISSUE #1155: Make the new bearer authentication support more standard compliant
Having built-in bearer authentication in the C#/TS clients is great but there are two annoying things in the current implementation:

  - The query string parameter name used by the TS client is non-standard and non-replaceable (the standard name is "access_token", not "signalRTokenHeader").

  - The `jwtBearer` properties/methods used in both clients have a name that assumes the token is a JWT, which is wrong as tokens are supposed to be opaque for clients.

/cc @Tratcher @davidfowl @moozzyk

### PR DESCRIPTION
**Pull request by anurse**
Doin the Pranav

### CODE REVIEW

**Comment by davidfowl** [comment]
@anurse whats left here?

**Comment by anurse** [comment]
Getting green builds, but I think it's just a flaky test.

**Comment by davidfowl** [comment]
We need to fix our flaky tests. A bunch of our PRs are still red.

**Comment by BrennanConroy** [comment]
Lets have a quick talk on Monday

**Pull request merged**
