### PR TITLE
Exclude connection ids in users

### PR DESCRIPTION
**Pull request by Gurgen**

### CODE REVIEW

**Comment by davidfowl** [comment]
We didn't approve this API, nor did you write a description in the pull request, nor does the code actually work. 

What feedback are you looking for?

**Comment by Gurgen** [comment]
This is a implementation of this [Issue](https://github.com/aspnet/SignalR/issues/939).

added excludedConnectionIds to User() method with default null parameter, so if need we can put there a collection of connection ids which we want to exclude.

**Comment by davidfowl** [comment]
> This is a implementation of this Issue.

Generally when you send a pull request you should write a description and that description should point to the issue you're solving. 

If you send a pull request as a demonstration of your idea that's fine, but please make it clear as part of the description. 

We have no plans to merge this.

**Comment by Gurgen** [comment]
I did it for me and wanted to share with others. This is a very useful functionality not only for me, I think.

**Comment by davidfowl** [comment]
> I did it for me and wanted to share with others. This is a very useful functionality not only for me, I think.

We'll think about the implications. I'm not a fan of adding exclude ids everywhere. We'll think about this more and come up with a recommendation. There might be a more general purpose feature here.

**Comment by Gurgen** [comment]
I have another view of the selection of message recipients, something like a Builder where you can add, as well as exclude recipients. For example, even if you do as recommended by KPixel in [Issue](https://github.com/aspnet/SignalR/issues/683) there is still no freedom of choice. That's what I think about it.

**Comment by davidfowl** [comment]
@Gurgen how is that different from a group?

**Comment by Gurgen** [comment]
And if we want to send a few groups?

**Comment by Gurgen** [comment]
Or to few groups and a few users? Or to users, who has some role?

**Comment by Gurgen** [comment]
With builder we can build list of recipients.
`RecipientBuilder.AddGroup().ExcludeConnectionId().AddUser()....Build()`

Something like this

**Pull request closed without merging**
