### PR TITLE
Removes resource consuming Redis subscription process from a global lock

### PR DESCRIPTION
**Pull request by Boychenko**
Removes resource consuming Redis subscription process from a global lock
- Adds a new structure to hold connection count to each subscription
- Makes global lock much shorter

### CODE REVIEW

**Comment by Boychenko** [comment]
Could you point me what tests did you run?

**Comment by Boychenko** [comment]
@BrennanConroy It will be much better if you give the command to execute to see perf results

**Comment by anurse** [comment]
The initial change to use this locking was to solve a correctness issue, we only did ad-hoc performance testing to verify that it didn't significantly degrade performance. In order to take a PR refactoring this code in the name of performance we need to see data showing the performance has improved. We don't currently have pre-written benchmarks for this scenario, so we don't have a specific command to run.

What prompted this change? Are you seeing a performance impact in a specific scenario? We generally avoid performance optimizations unless there's specific data (memory profiles, traces, benchmarks) driving the decision.

**Comment by Boychenko** [comment]
@anurse I've made a new benchmark for concurrent connections. To show improvement I've added network delay 1ms for all methods `TestRedisServer`.
Result:
### Before
``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.431)
Intel Core i7-4710HQ CPU 2.50GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=2435776 Hz, Resolution=410.5468 ns, Timer=TSC
.NET Core SDK=2.1.300-rc1-008673
  [Host]     : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT


```
|    Method | UserCount | GroupCount |      Mean |     Error |    StdDev |   Op/s |   Gen 0 | Allocated |
|---------- |---------- |----------- |----------:|----------:|----------:|-------:|--------:|----------:|
| **JoinLeave** |         **1** |          **1** |  **15.49 ms** | **0.6007 ms** | **0.5619 ms** | **64.545** | **31.2500** |    **7.8 KB** |
| **JoinLeave** |         **1** |         **15** |  **69.25 ms** | **0.3711 ms** | **0.3471 ms** | **14.441** |       **-** |    **7.8 KB** |
| **JoinLeave** |        **20** |          **1** |  **80.20 ms** | **0.4067 ms** | **0.3606 ms** | **12.470** | **62.5000** |    **7.8 KB** |
| **JoinLeave** |        **20** |         **15** | **109.05 ms** | **2.1173 ms** | **2.3534 ms** |  **9.170** | **62.5000** |    **7.8 KB** |

### After
``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.431)
Intel Core i7-4710HQ CPU 2.50GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=2435776 Hz, Resolution=410.5468 ns, Timer=TSC
.NET Core SDK=2.1.300-rc1-008673
  [Host]     : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT


```
|    Method | UserCount | GroupCount |     Mean |     Error |    StdDev |   Median |  Op/s |   Gen 0 | Allocated |
|---------- |---------- |----------- |---------:|----------:|----------:|---------:|------:|--------:|----------:|
| **JoinLeave** |         **1** |          **1** | **13.66 ms** | **0.2730 ms** | **0.5260 ms** | **13.48 ms** | **73.19** | **31.2500** |    **7.8 KB** |
| **JoinLeave** |         **1** |         **15** | **12.27 ms** | **0.2436 ms** | **0.4002 ms** | **12.19 ms** | **81.49** | **31.2500** |    **7.8 KB** |
| **JoinLeave** |        **20** |          **1** | **20.87 ms** | **0.2816 ms** | **0.2635 ms** | **20.88 ms** | **47.92** | **31.2500** |    **7.8 KB** |
| **JoinLeave** |        **20** |         **15** | **11.97 ms** | **0.3046 ms** | **0.7120 ms** | **11.73 ms** | **83.53** | **62.5000** |    **7.8 KB** |

**Comment by anurse** [comment]
Awesome work @Boychenko ! We try to make sure that when we're taking a performance-related PR we know precisely what benefit it has, so thanks very much for the benchmark data. We'll take a look at the data and the PR!

**Comment by BrennanConroy** [comment]
@Boychenko Nice work writing a benchmark! Unfortunately the `TestRedisServer` is very untested and has bugs around keeping subscriptions around which heavily affects your benchmarking scenarios making the numbers unusable.

I'm curious, did you see a real world slow down because of this lock?

We can't take this change unless we know for a fact that there is real perf concerns.

**Comment by Boychenko** [comment]
@BrennanConroy What bugs in `TestRedisServer` affected my benchmarking scenarios?
I think real world scenario is quite obvious. When a few users connect to the server or join groups at the same time global lock doesn't make this process faster.
I'm not saying that library starts to be not usable without this improvement but it can be faster.

**Comment by Boychenko** [comment]
Hi
Any decision about this PR?
Should close it?

**Comment by anurse** [comment]
I'm going to close this. I think we should gather more data on this if we want to take a performance improvement here. At the moment, I don't think this is a high priority, but if we start getting feedback about performance problems here we can revisit it.

**Pull request closed without merging**
