### PR TITLE
Add ArtifactInfo into design-time build

### PR DESCRIPTION
**Pull request by natemcmaster**
Allows aspnet/universe to acquire a list of expected outputs (artifact info) without building aspnet/SignalR

### CODE REVIEW

**Comment by natemcmaster** [comment]
Two test failures in Travis-CI Linux, but they appear to be unrelated to this change. Is this known?

```
[xUnit.net 00:00:01.8281447]   Starting:    Microsoft.AspNetCore.SignalR.Tests (parallel test collections = on, max threads = 16)
Application startup exception: System.NotSupportedException: Duplicate definitions of 'OverloadedMethod'. Overloading is not supported.
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.DiscoverHubMethods() in /_/src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs:line 524
``

**Comment by BrennanConroy** [comment]
Thats not the actual failing test :P
But don't block your change on the 2 failing tests

**Comment by natemcmaster** [comment]
I'll take that as a :shipit:?

**Comment by BrennanConroy** [comment]
One, sec, I'll look at the actual change :D

**Pull request merged**
