### PR TITLE
Update TS docs for docs.microsoft.com generation

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
It's already been pushed live
https://docs.microsoft.com/en-us/javascript/api/?view=signalr-js-latest

You have nothing to compare to since we didn't have the docs before.

**Comment by davidfowl** [comment]
Any details about why you had to add @aspnet/signalr everywhere?

**Comment by BrennanConroy** [comment]
Something about how docfx creates the xref links, it needs the fullname otherwise it displays `<xref: HttpResponse>` for example instead of a link.

**Comment by BrennanConroy** [comment]
@Eilon for 2.1.4 consideration

**Comment by BrennanConroy** [comment]
@Eilon https://github.com/aspnet/SignalR/issues/2529

**Comment by BrennanConroy** [comment]
@anurse Could you do a quick pass again before I merge? I changed some things back to internal now that it's supported.

**Pull request merged**
