### PR TITLE
Adding README to npm module

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by moozzyk** [comment]
We decided not to take this for alpha1 so rebasing on dev

**Comment by moozzyk** [comment]
:up::date: - Rebased again - this time on the rel/1.0.0-alpha2 branch

**Comment by davidfowl** [comment]
Maybe add some fancy badges 😄 https://www.npmjs.com/package/socket.io

**Comment by moozzyk** [comment]
We can think about adding badges post alpha-2

**Pull request merged**
