### PR TITLE
updated js sample with temporary dependencies

### PR DESCRIPTION
**Pull request by bradygaster**

### CODE REVIEW

**Comment by mikaelm12** [comment]
Context here - Issue: https://github.com/aspnet/SignalR/issues/2874

**Comment by bradygaster** [comment]
Thanks @mikaelm12 - I am in agreement, we should wait until the larger discussion happens.

**Comment by anurse** [comment]
This needs to be on the `release/2.1` branch. The readme change is incorrect for 2.2 and 3.0.

**Comment by anurse** [comment]
I can't just retarget it, it blows up the world :). @bradygaster can you rebase on `release/2.1`

**Comment by bradygaster** [comment]
yes @anurse i can do that. sorry for the confusion.

**Pull request closed without merging**
