### PR TITLE
fix #3144 by failing tests on CI if no browsers

### LINKED ISSUE #3144: Browser tests aren't running in TeamCity CI
Our browser tests aren't running on every build in TeamCity. The tests just silently no-op if there are no suitable browsers, and some agents don't have the right browsers. We should:

1. Change the tests to fail loudly if no browsers are available when running on the CI
1. Install at least a browser on each TeamCity agent

Note: The tests **are** running on VSTS so we have some coverage.

### PR DESCRIPTION
**Pull request by analogrelay**
fixes #3144

If there are no browsers available, our functional tests simply no-op. However, on the CI we want the tests to fail so we ensure we get some browser test coverage in CI.

### CODE REVIEW

**Comment by anurse** [comment]
ping reviewers: it did indeed fail and I've now uncommented the code that adds the browsers.

**Comment by BrennanConroy** [comment]
Oh good, you're hitting the issue I was trying to fix. VSTS Mac doesn't have Chrome or Firefox, so it fails now. I was trying to enable all browsers for CI builds but couldn't get the environment variable working.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/pull/3170/commits/cd9296d946f24f274414a5e12f2f30d03f6fa798

**Comment by anurse** [comment]
Waiting to rebase on #3202 which should resolve most of the build failures.

**Comment by muratg** [comment]
SignalR work has moved to aspnetcore repo, and this repo will be archived. If you're still interested in pursuing this PR, please move it over to aspnetcore. Thanks.

**Pull request closed without merging**
