### PR TITLE
Add typed HubContext

### PR DESCRIPTION
**Pull request by FTWinston**
As per #722, it should be possible to use strongly-typed client methods when working with a hub context, rather than a hub.

This PR adds a version of HubContext with a second generic type parameter in order to give access to a typed IHubClients, and seems to "just work" when used via dependency injection with a typed hub.

### CODE REVIEW

**Comment by moozzyk** [comment]
Can you show this is used end-to-end?

**Comment by FTWinston** [comment]
@moozzyk 
All I've done to use this is:
`_hubContext = serviceProvider.GetRequiredService<IHubContext<MyHubClass, MyClientInterface>>();`
and then
`_hubContext.Clients.Group(GroupName).SomeInterfaceCommand(param1, param2);`

I don't think there's much more to it. You want a formal test?

**Comment by FTWinston** [comment]
Ideally I'd make `IHubContext<THub>` extend `IHubContext<THub, T>` where `T` is `IClientProxy`
... but I can't do that without changing `HubContext<THub>` to have `THub` be `Hub<IClientProxy>` instead of just `Hub`.
And I can't do _that_ without changing HubEndPoint, or adding a new "typed" version of that.

**Comment by FTWinston** [comment]
I'm a bit stuck. I can't get anything beyond d3ae3abe2acb to compile.

I just get the _Package references have not been pinned_ error, but my attempts to [run build.cmd](https://github.com/aspnet/Home/wiki/Building-from-source) fail because this directory is empty: %USERPROFILE%\.dotnet\buildtools\korebuild\2.1.0-preview1-15494

I found KoreBuild files [here](https://github.com/aspnet/BuildTools/tree/dev/files/KoreBuild) and put them in that directory, but build.cmd /t:Pin gives me _error MSB4057: The target "Pin" does not exist in the project._

Could someone point me at where/how I should be getting KoreBuild files from? Alternatively, if anyone else wants to adopt this and merge in updates themselves, feel free.

**Comment by moozzyk** [comment]
@FTWinston - we were busy shipping alpha1 and did not have a chance to complete processing your PR. Now that we shipped will get to it soon. 

The way I "fix" the package not pinned error is `git clean -xdf` in the repo and run build.cmd. I will find an email from @natemcmaster on the proper way of fixing this unless he wants to chime in.

**Comment by BrennanConroy** [comment]
The test doesn't actually use `IHubContext<THub, T>`. You had a good example above, try writing a test around that?

**Comment by FTWinston** [comment]
Thanks @moozzyk, but when I do that and run build.cmd, it spits out the _packages not pinned error_, and attempting to pin gives the error I listed above.

@BrennanConroy ... oops! Yeah looking at the title of the PR, that's embarassing... will do.

**Comment by moozzyk** [comment]
@FTWinston I rebased your PR on the latest dev and fixed some compilation and formatting issues. Ran build.cmd and it passed. I opened a new PR here: https://github.com/aspnet/SignalR/pull/890. Not sure if you want to update your PR based on what I did or review what I sent and iterate on this?

**Comment by FTWinston** [comment]
That's great @moozzyk, let's go with that. Less fuss that way!

**Pull request closed without merging**
