### PR TITLE
React to logging changes

### PR DESCRIPTION
**Pull request by BrennanConroy**
@pakrym

### CODE REVIEW

**Comment by BrennanConroy** [comment]
@pakrym Approved

Tests failing for other reasons

**Comment by davidfowl** [comment]
Why are they failing?

**Comment by pakrym** [comment]
@JunTaoLuo logging change.

**Comment by pakrym** [comment]
https://github.com/aspnet/Logging/commit/625e12229cfb11ecbb38629e6c8ad02a795b9192

**Pull request merged**
