### PR TITLE
[WIP] Deflaking Tests

### PR DESCRIPTION
**Pull request by anurse**
It's only flaky in travis so I'm opening a PR to play around with some things.

### CODE REVIEW

**Comment by davidfowl** [comment]
Why is travis failing on every PR

**Comment by anurse** [comment]
That's the point of this PR, start reducing that :). Hopefully there are useful logs, but I bet this failure is a different test than I've been chasing (just because flaky tests are a pain)

**Comment by anurse** [comment]
FYI, there's no change here yet, this is just logging and using a PR to trigger Travis so I can see and debug the flaky test.

**Comment by anurse** [comment]
Think I found a way to resolve some of the flakiness around WebSockets while also finding a product bug. We didn't handle the close timeout very well and relied on `Task.Delay` to time us out. I think `Task.Delay` is less reliable than `CancellationTokenSource.CancelAfter` after looking at the code a little. Might look at applying this elsewhere.

**Comment by mikaelm12** [comment]
@anurse Gonna go ahead and close this for you

**Pull request closed without merging**
