### PR TITLE
Use invariant culture and ordinal comparisons

### PR DESCRIPTION
**Pull request by JamesNK**
- Ordinal comparison on group names, connection IDs, invocation IDs and headers
- A couple of other minor culture fixes

### CODE REVIEW

**Comment by JamesNK** [comment]
https://github.com/aspnet/SignalR/issues/1905

**Comment by JamesNK** [comment]
In the future might want to consider some code analysis for culture comparisons.

**Comment by BrennanConroy** [comment]
Do we have a testing strategy for different cultures?

**Comment by JamesNK** [comment]
Simplest way to do it is run the tests again with a different culture.

**Pull request merged**
