### PR TITLE
Making `OrTimeout` common

### PR DESCRIPTION
**Pull request by moozzyk**
For now I just use linked source. If there is more common utils to share we can create a common test project.

### CODE REVIEW

**Comment by moozzyk** [comment]
@anurse - we also have a copy of `OrTimeout` in WebSockets tests. Do you want me to get rid of it and use the one I moved to `Common`

**Comment by anurse** [comment]
Yeah, yours is much simpler... I'm... not sure what I was thinking when I wrote mine :)

**Comment by moozzyk** [comment]
:up::date:

**Comment by anurse** [comment]
Ah, I remember why I wrote mine that way. I wrote the cancellation token version first for other purposes and just kinda kept using that technique. I still like yours way better ;).

**Pull request merged**
