### PR TITLE
Remove message content from JS client logging

### PR DESCRIPTION
**Pull request by JamesNK**
https://github.com/aspnet/SignalR/issues/1449

### CODE REVIEW

**Comment by davidfowl** [comment]
> Looks good to me. @davidfowl if you want to introduce a flag to re-enable this, file an issue for that and we can track it later. This change is required to ship though, so I'd rather get it in ASAP.

Ummm, naw. See the problem is when you use binary you can't really use any other tools to look at the data, so I think the flag *has* to be added along with the feature.

**Comment by JamesNK** [comment]
Where does the flag exist? How does a dev set it?

**Comment by davidfowl** [comment]
> Where should the flag exist? How does a dev set it?

All of our ts flags are currrently on an options object passed into the hubConnection constructor. I imagine it would go there.

**Comment by anurse** [comment]
> See the problem is when you use binary you can't really use any other tools

What do you expect our logging to output? Base64? Hex?

**Pull request merged**
