### PR TITLE
Pascal case formatted log parameter names

### PR DESCRIPTION
**Pull request by BrennanConroy**
#1087

### CODE REVIEW

**Comment by davidfowl** [comment]
Can you use a tool and tell me if ConnectionId clashes with the Kestrel ConnectionId

**Comment by BrennanConroy** [comment]
Tomorrow, sure

**Comment by davidfowl** [comment]
> Presuming ConnectionId doesn't clash or you rename it if it does: LGTM

Yep. I think it does. Last time I used Seq I believe there was ConnectionId from Kestrel and connectionId from SignalR.

**Comment by BrennanConroy** [comment]
Renaming to `SocketsConnectionId`

**Pull request merged**
