### PR TITLE
[Redis] Don't wait for group ack when you're the only server

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by moozzyk** [comment]
I am not a fan of this change. It makes the code more complex without almost any benefits. First, running one server with scaleout should almost never happen. Second, if it happens ACKs should be very fast.

**Comment by davidfowl** [comment]
Agreed. We thought about doing this with the original signalr as well and decided against special code paths.

**Comment by BrennanConroy** [comment]
@moozzyk and I talked about this yesterday, and I have a more generic solution that I wanted to run by you.

You send the group add/remove and get back the number of servers sent to, then each server sends an ACK back, and a special ACK if they did the action. Then we can check the amount of ACKs received vs. the number from publish and finish waiting for the ACK or if we get the ACK saying the action was completed we can finish waiting for the ACK.

**Comment by moozzyk** [comment]
Do you even need a special ACK? You just wait for everyone to ACK without needing to know whether they removed the user or not (unless the idea is to ignore other ACKs if you received the one that did the action)

**Comment by BrennanConroy** [comment]
Yeah, the idea was we could ignore the other ACKs.

**Comment by davidfowl** [comment]
@BrennanConroy Are you going to update this change?

**Comment by BrennanConroy** [comment]
If we're okay with making the change to ACKs then I can

**Comment by davidfowl** [comment]
Lets's not right now. We can optimize later.

**Comment by davidfowl** [comment]
File an issue as a suggestion to improve the redis impl.

**Pull request closed without merging**
