### PR TITLE
Fix negotiate test

### PR DESCRIPTION
**Pull request by mikaelm12**
This pr: https://github.com/aspnet/SignalR/pull/3050 introduced a break.

Fixing it here.

### CODE REVIEW

**Comment by mikaelm12** [comment]
This commit: https://github.com/aspnet/SignalR/commit/2e41a7063b8731676cdc180277a4e137ddb2394b removed an API that the above commit depended on.

**Comment by BrennanConroy** [comment]
Oh... already fixed it and pushed

**Comment by mikaelm12** [comment]
Did you push directly to release/2.2?

**Comment by BrennanConroy** [comment]
Yep

**Comment by mikaelm12** [comment]
And after I sent this pr ..

**Pull request closed without merging**
